### ISSUE TITLE
missing dependencies / environment compatibilities

### ISSUE THREAD

**Issue by orbitbus** [probcomp/crosscat#105]
Could you please document the exact Ubuntu environments that were used for pip install?
Pip notoriously doesn't work on untested versions. I have 14.04 but am happy to change to what works.
Any prerequisites?

It won't install as it gets stuck with numerous Cython issues which dependency it doesn't resolve properly (surprise. I hate pip)
Also, is Ubuntu the only environment that works for the pip install? I tried Windows 7 but got stuck somewhere in Visual C++ compilations.

**Comment by orbitbus** [comment]
end rant.

**Comment by axch** [comment]
Ranty style notwithstanding, @orbitbus makes a good point.  It would be nice to
- [ ] List the crosscat installation instructions
- [ ] In the form of a Dockerfile
- [ ] and make a Jenkins job to routinely runs tests against it

**Comment by riastradh-probcomp** [comment]
Parts (1) and (2) are done in <https://github.com/probcomp/crosscat/commit/1ebb1aa072f332dd26a6feb162d287773eb3cc6c>.

**Comment by riastradh-probcomp** [comment]
Also: Yes, we don't support Windows right now.  If you make it work, great, send a (nonintrusive) patch, but we've never tried and have no plans to try.

**Comment by fsaad** [comment]
Part (3) is at https://probcomp-4.csail.mit.edu/job/crosscat-master-crashes/
