### ISSUE TITLE
Tests segfault

### ISSUE THREAD

**Issue by gregory-marton** [probcomp/crosscat#42]
[probcomp-4  pc/crosscat]$ py.test
================================================================== test session starts ===================================================================
platform linux2 -- Python 2.7.6 -- pytest-2.5.1
plugins: flaky
collecting 0 items / 4 errorsSegmentation fault
[probcomp-4  pc/crosscat]$

**Comment by riastradh-probcomp** [comment]
Should be fixed now.  Try again?

**Comment by gregory-marton** [comment]
I just noticed this was waiting on me... :-p

So running bare py.test still segfaults for me on both probcomp-4 and osx. But that's not the recommended thing to do. We should be doing ./check.sh instead, and there's likely to be a meaningful difference. So let's just call bare py.test unsupported. Does ./check.sh work?

On probcomp-4, yes.  Or rather, appears to. There's a part after the test that just spews output without indicating whether that output is good or bad.
On osx yes kinda, but no. That part after the test just outright fails, and leaves me with no confidence that everything worked as it should: 

========================== 82 passed in 0.81 seconds ===========================
g++ -c src/Cluster.cpp -o obj/Cluster.o -pg -O2  -Wall -Werror -std=c++03 -lm -Iinclude/CrossCat
clang: error: -lm: 'linker' input unused
make: *** [obj/Cluster.o] Error 1

**Comment by riastradh-probcomp** [comment]
Date: Tue, 22 Dec 2015 11:39:17 -0800
   From: Gregory Marton <notifications@github.com>

   So running bare py.test still segfaults for me on both probcomp-4
   and osx. But that's not the recommended thing to do. We should be
   doing ./check.sh instead, and there's likely to be a meaningful
   difference. So let's just call bare py.test unsupported. Does
   ./check.sh work?

Running py.test ought to work if you have installed Crosscat, and in
particular the same version of Crosscat.  All that check.sh does
beyond running py.test is (a) make a clean build and then (b) set
PYTHONPATH.

   On probcomp-4, yes.  Or rather, appears to. There's a part after
   the test that just spews output without indicating whether that
   output is good or bad.  On osx yes kinda, but no. That part after
   the test just outright fails, and leaves me with no confidence that
   everything worked as it should:

   ========================== 82 passed in 0.81 seconds ===========================
   g++ -c src/Cluster.cpp -o obj/Cluster.o -pg -O2  -Wall -Werror -std=c++03 -lm -Iinclude/CrossCat
   clang: error: -lm: 'linker' input unused
   make: *** [obj/Cluster.o] Error 1

The makefile needs to be rewritten.  Among many other problems it has,
the .cpp -> .o rule should not pass -lm to the C++ compiler.  That
part should be easy to fix, though.

**Comment by gregory-marton** [comment]
d00380f

**Comment by raxraxraxraxrax** [comment]
Confirmed fix on a fresh OS X build.
