### ISSUE TITLE
Error in running the example (crosscat.settings module)

### ISSUE THREAD

**Issue by namp** [probcomp/crosscat#78]
python crosscat/examples/dha_example.py crosscat/www/data/dha.csv --num_chains 2 --num_transitions 2

Traceback (most recent call last):
  File "crosscat/examples/dha_example.py", line 25, in <module>
    import crosscat.settings as S
ImportError: No module named settings

Machine: Ubuntu 15.04 x86_64 with Anaconda. Crosscat built from github source (same error with simple pip install)

**Comment by riastradh-probcomp** [comment]
Fixed in e1cb3ba4f76eaa716c1fcc8bf34664f2a887fc25.
